node('build001-dmz.comaas-lp.ams1.cloud') {
    stage('Test stage') {

        library "commonFunctions@${sha1}"
        commonFunctions.helloWorld()

        /*commonFunctions.checkoutGithubRepo(ghprbActualCommit, 'ecg-comaas-central', ghprbAuthorRepoGitUrl)

        String gitBranchName = sh(
                script: "cd ecg-comaas-central; git rev-parse --abbrev-ref HEAD",
                returnStdout: true
        ).trim()

        echo "Branch name: $gitBranchName"

        library "commonFunctions@${gitBranchName}"

        commonFunctions.helloWorld()*/
    }
}