node('qa') {
    stage('Test stage') {
        String gitBranchName = sh(
                script: "git rev-parse --abbrev-ref HEAD",
                returnStdout: true
        ).trim()

        echo "Branch name: $gitBranchName"
    }
}