#!/usr/bin/env groovy
import java.text.SimpleDateFormat

library "commonFunctions@${PROVIDED_PIPELINE_BRANCH}"

void packageComaas(String version) {
    echo "Packaging Comaas version $version"
    sh "cd ecg-comaas-central && " +
            "mvn --settings etc/settings.xml versions:set -DnewVersion=\"$version\" -DgenerateBackupPoms=false &&" +
            "bin/build.sh -p && " +
            "mkdir -p builds && " +
            "mv -v distribution/target/*.tar.gz builds/comaas-${version}.tar.gz"

    echo "Creating Docker image for $version"
    final String dockerImageName = "dock.es.ecg.tools/comaas/comaas:${version}"
    final String tmpDir = "docker_image_src"
    sh "cd ecg-comaas-central && " +
            "rm -rf ${tmpDir} && " +
            "mkdir -p ${tmpDir} && " +
            "tar xf builds/comaas-${version}.tar.gz -C ${tmpDir} && " +
            "docker build --no-cache --pull --tag ${dockerImageName} ."
    commonFunctions.loginToDocker()
    sh "docker push $dockerImageName"
    sh "docker image remove $dockerImageName"
}

// p contains [tenant, version]
distribute = { String[] p ->
    String tenant = p[0], version = p[1]
    packageComaas(tenant, version)
}

void setEnvVars() {
    env.MAVEN_HOME = "/usr/share/apache-maven"
    env.PATH = "$env.MAVEN_HOME/bin:$env.PATH"
}

static String createVersionString(String buildNr) {
    return new SimpleDateFormat("yyyy.MM.").format(new Date()) + buildNr
}

node('build') {
    setEnvVars()

    PROVIDED_VERSION = PROVIDED_VERSION.trim()

    if (PROVIDED_VERSION != '' && !(PROVIDED_VERSION =~ /^\d{4}\.\d{2}\..+/)) {
        error("Provided version does not have the form 'YYYY.mm.xxx', or empty. Leave empty to create a new version on master.")
    }

    String version, gitHash
    Boolean createTag = false

    if (PROVIDED_VERSION == '') {
        gitHash = commonFunctions.getMasterSha()

        echo "Checking if commit $gitHash already has a version tag"

        commonFunctions.checkoutComaasCentralRepo(gitHash)

        version = sh(
                script: "cd ecg-comaas-central; git show-ref --dereference --tags | grep \"^$gitHash\" | sort | head -1 | sed -e 's~.* refs/tags/~~' -e 's/\\^{}//'",
                returnStdout: true
        ).trim()

        if (version != '') {
            echo "PROVIDED_VERSION was empty, but commit $gitHash already has version $version. Rebuilding but not making a new version tag"
        } else {
            version = createVersionString(env.BUILD_NUMBER as String)
            createTag = true
            echo "PROVIDED_VERSION was empty, creating new version $version on commit $gitHash"
        }
    } else {
        version = PROVIDED_VERSION
        gitHash = commonFunctions.getGitHashForTag(version)
        echo "Rebuilding version $version from commit $gitHash"
    }

    echo "Packaging version $version using git hash $gitHash"
    currentBuild.description = "$version $PROVIDED_TENANT"

    if (PROVIDED_TENANT == 'all' || PROVIDED_TENANT == '') {
        tenants = commonFunctions.allTenants()
    } else {
        tenants = [PROVIDED_TENANT]
    }

    buildSteps = ["failFast": false]
    buildSteps += [((String) "package-all"): commonFunctions.wrapWithStepDefinition(['all', version], distribute, gitHash, "Package artifact for all")]
    parallel buildSteps

    if (createTag) {
        stage("Tag commit with version") {
            node('lp') {
                commonFunctions.tagWithVersion(gitHash, version)
            }
        }
    }
}
