#!/usr/bin/env groovy

def libraryVersion = (ghprbPullId == null) ? "master" : "pr/$ghprbPullId"
libraryVersion = "pull/130/head"

library "commonFunctionsDev@130"

node('prod') {
    commonFunctions.sendToSlack("#abcdef", "test", "HELLO WORLD")
    sh "env | sort"
    sh "ls -lash"
}
