version: '3'
services:
  cassandra:
    image: docker-registry.ecg.so/comaas/cassandra_data:0.0.11
    ports:
    - "9042:9042"
    environment:
      SERVICE_9042_NAME: cassandra
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.11.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - zookeeper
  activemq:
    image: webcenter/activemq
    ports:
      - "8161:8161"
      - "61616:61616"
  rabbitmq: # testing AU (Gumbot related stuff)
    image: rabbitmq:3-management
    volumes:
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./rabbitmq/definitions.json:/opt/definitions.json:ro
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    ports:
      - "5672:5672"
      - "15672:15672"
  mysql: # testing AU, EK
    image: mysql:5.7.21
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_USER: mysql_guest
      MYSQL_PASSWORD: mysql_guest
  elasticsearch5:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
      ports:
      - "9250:9200"
      - "9350:9300"
      environment:
        discovery.type: "single-node"
        xpack.security.enabled: "false"
        cluster.name: "elasticsearch"
        SERVICE_9250_NAME: elasticsearch5
        SERVICE_9250_CHECK_SCRIPT: curl -s http://elasticsearch5:9200/_cat/health?h=status | grep -q green
      volumes:
      - "./elasticsearch5/run_with_mapping.sh:/usr/share/elasticsearch/run_with_mapping.sh"
      - "./elasticsearch5/message_mapping.json:/usr/share/elasticsearch/message_mapping.json"
      command:
          - ./run_with_mapping.sh
