version: '3'
services:
  cassandra:
    image: docker-registry.ecg.so/comaas/cassandra_data:0.0.11
    ports:
    - "9042:9042"
    environment:
      SERVICE_9042_NAME: cassandra
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - zookeeper
  activemq:
    image: webcenter/activemq
    ports:
      - "8161:8161"
      - "61616:61616"
