#!/bin/bash
adduser --system replyts2
addgroup replyts2 || true
usermod -a -G replyts2 replyts2 || true
mkdir -p /var/log/replyts2
chmod -R 755 /var/log/replyts2
chown -R replyts2. /var/log/replyts2

mkdir -p /var/spool/replyts2
chmod -R 755 /var/spool/replyts2
chown -R replyts2. /var/spool/replyts2
