tenants:
  disabled: []
smokeTest:
  version:
      lp:
        default: 0.1.28
      prod:
        default: 0.1.28
  runPostMessageTests:
      lp:
        mp: true
        default: false
      prod:
        default: false
