# the number of instances of comaas deployed on production as API/http only nodes in Nomad
instances:
  lp: 2
  prod:
    http:
      ebayk: 3
      gtau: 6
      gtuk: 6
      it: 3
      kjca: 6
      mde: 3
      mp: 12
      ar: 3
      sg: 3
      mx: 3
      za: 3
    newmsg:
      ebayk: 3
      gtau: 6
      gtuk: 6
      it: 3
      kjca: 6
      mde: 3
      mp: 12
      ar: 3
      sg: 3
      mx: 3
      za: 3
