# the number of instances of comaas deployed on production as API/http only nodes in Nomad
# LP always gets 3 instances per tenant
instances:
  ebayk: 6
  gtau: 6
  gtuk: 6
  it: 3
  kjca: 6
  mde: 3
  mp: 6
